services:
  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
     - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  # Backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/tickets
      - IPIFY_URL=https://api.ipify.org?format=json

  # Banco de Dados
  postgres:
    image: postgres:13
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tickets
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Monitoramento - Prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - backend

  # Monitoramento - Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - app-network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge